### ISSUE TITLE
Not working .... 

### ISSUE THREAD

**Issue by mikeerickson** [JesseLeite/dotfiles#1]
So, I thought I would give this a try and see how it goes.

I have placed the after.sh in my homestead directory (see screen) but perform `homestead up` doesn't seem to do anything.

http://d.pr/i/113I2

You mentioned in the installation note that it should be placed in `.homestead` directory, but that doesn't actually exist (was it a typo, directory is not hidden)

**Comment by mikeerickson** [comment]
Welcome, to my surprise, there actually IS a ~/.homestead directory, try it again now ;-)  And how it all works as expected (mea culpa)

**Comment by jesseleite** [comment]
Yeah not typo.  Must be -global- install as per Homestead's docs: http://i.imgur.com/LfhGkA7.png

Let me know how it works out :)

**Comment by mikeerickson** [comment]
@JerseyMilker 

Works great thus far...

Where do I change the name 'Facade :: '

**Comment by mikeerickson** [comment]
@JerseyMilker So, it seems I need to 
- fork repo (as mentioned)
- edit the `jersey-homestead.zsh-theme` (or whatever I call it)
- customize the theme file as I need (in this case, line 15)
- reference new repo in after.sh file

Capichè :-)

**Comment by jesseleite** [comment]
jersey-homestead.zsh-theme, you got it!  And yes, if you fork the repo and change after.sh to reference your repo, then you homestead up will grab your customizations :)

Update: I just submitted pull requests to your repo for these things.
